### ISSUE TITLE
[Bug]: 使用SPU跑pir任务，使用旧的setup目录一直会卡死

### ISSUE THREAD

**Issue by ccch1oe** [secretflow/psi#18]
### Issue Type

Support

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.6.0b0 

### OS Platform and Distribution

CentOS Linux 7

### Python Version

3.8

### Current Behavior?

在跑pir的时候，如果每次生成新的setup文件，pir任务是正常的。
如果使用旧的setup文件，两方就会卡死。alice方一直不会进入到pir_query的方法。
ray的启动命令
ray start --head --node-ip-address=$nodeip --port=$nodeport --include-dashboard=False --disable-usage-stats

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by yyf1986** [comment]
bob
```
INFO:root:sf init
2023-11-28 08:54:17,772 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.1.251.75:5902...
2023-11-28 08:54:17,785 INFO worker.py:1538 -- Connected to Ray cluster.
2023-11-28 08:54:17 INFO api.py:147 [bob] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': '10.1.251.74:59301', 'bob': '10.1.251.75:59301'}, 'CURRENT_PARTY_NAME': 'bob', 'TLS_CONFIG': {}}
2023-11-28 08:54:17 INFO cleanup.py:58 [bob] --  Start check sending thread.
2023-11-28 08:54:17 INFO cleanup.py:67 [bob] --  Start check sending monitor thread.
2023-11-28 08:54:18 INFO barriers.py:235 [bob] --  Succeeded to create receiver proxy actor.
(ReceiverProxyActor pid=40749) 2023-11-28 08:54:18 INFO grpc_proxy.py:306 [bob] --  ReceiveProxy binding port 59301, options: (('grpc.enable_retries', 1), ('grpc.so_reuseport', 0), ('grpc.max_send_message_length', 524288000), ('grpc.max_receive_message_length', 524288000), ('grpc.service_config', '{"methodConfig": [{"name": [{"service": "GrpcService"}], "retryPolicy": {"maxAttempts": 5, "initialBackoff": "5s", "maxBackoff": "30s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}]}'))...
(ReceiverProxyActor pid=40749) 2023-11-28 08:54:18 INFO grpc_proxy.py:326 [bob] --  Successfully start Grpc service without credentials.
2023-11-28 08:54:20 INFO barriers.py:283 [bob] --  SenderProxyActor has successfully created.
2023-11-28 08:54:20 INFO barriers.py:438 [bob] --  Try ping ['alice'] at 0 attemp, up to 3600 attemps.
2023-11-28 08:54:23 INFO barriers.py:438 [bob] --  Try ping ['alice'] at 1 attemp, up to 3600 attemps.
2023-11-28 08:54:26 INFO barriers.py:438 [bob] --  Try ping ['alice'] at 2 attemp, up to 3600 attemps.
2023-11-28 08:54:26 INFO pir.py:87 [bob] --  spu init
2023-11-28 08:54:26 INFO pir.py:119 [bob] --  spu start pir
(SPURuntime(device_id=bob, party=bob) pid=40975) INFO:root:rank:1 send 9 sync status
Traceback (most recent call last):
2023-11-28 08:56:34 WARNING cleanup.py:99 [bob] --  Failed to send ObjectRef(8c37cb6d2e1f67561c749a9c8e4c31e9e64c53d00e00000001000000) with error: ray::SenderProxyActor.send() (pid=40860, ip=10.1.251.75, repr=<fed.proxy.barriers.SenderProxyActor object at 0x7f71507bb820>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.pir_query() (pid=40975, ip=10.1.251.75, repr=SPURuntime(device_id=bob, party=bob))
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1328, in pir_query
    report = pir.pir_server(self.link, config)
  File "/usr/local/lib/python3.8/site-packages/spu/pir.py", line 39, in pir_server
    report_str = libspu.libs.pir_server(link, config.SerializeToString())
RuntimeError: what: 
        [external/yacl/yacl/link/transport/channel.cc:351] Get data timeout, key=root-0:1:ALLGATHER
Stacktrace:
#0 yacl::link::Context::RecvInternal()+0x7ff2a68b71f7
#1 yacl::link::AllGatherImpl<>()+0x7ff2a68b1c61
#2 yacl::link::AllGather()+0x7ff2a68b20e3
#3 spu::psi::SyncWait<>()+0x7ff2a654c54a
#4 spu::pir::PirServer()+0x7ff2a65567c4
#5 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7ff2a5359e4f
#6 pybind11::cpp_function::dispatcher()+0x7ff2a5325f06
#7 PyCFunction_Call+0x4e0212

stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7ff2a68b71f7
#1 yacl::link::AllGatherImpl<>()+0x7ff2a68b1c61
#2 yacl::link::AllGather()+0x7ff2a68b20e3
#3 spu::psi::SyncWait<>()+0x7ff2a654c54a
#4 spu::pir::PirServer()+0x7ff2a65567c4
#5 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7ff2a5359e4f
#6 pybind11::cpp_function::dispatcher()+0x7ff2a5325f06
#7 PyCFunction_Call+0x4e0212
  File "/root/pir.py", line 120, in <module>
2023-11-28 08:56:34 WARNING cleanup.py:102 [bob] --  Signal self to exit.
*** SIGTERM received at time=1701161794 on cpu 64 ***
2023-11-28 08:56:34 INFO cleanup.py:106 [bob] --  Check sending thread was exited.
PC: @     0x7f1a5620e838  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f1a56212ce0  (unknown)  (unknown)
[2023-11-28 08:56:34,494 E 40565 40565] logging.cc:361: *** SIGTERM received at time=1701161794 on cpu 64 ***
[2023-11-28 08:56:34,494 E 40565 40565] logging.cc:361: PC: @     0x7f1a5620e838  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2023-11-28 08:56:34,494 E 40565 40565] logging.cc:361:     @     0x7f1a56212ce0  (unknown)  (unknown)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 2175, in pir_query
    return dispatch(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 550, in pir_query
    return sfd.get(res)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 134, in get
    return fed.get(object_refs)
  File "/usr/local/lib/python3.8/site-packages/fed/api.py", line 395, in get
    values = ray.get(ray_refs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_query() (pid=40975, ip=10.1.251.75, repr=SPURuntime(device_id=bob, party=bob))
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1328, in pir_query
    report = pir.pir_server(self.link, config)
  File "/usr/local/lib/python3.8/site-packages/spu/pir.py", line 39, in pir_server
    report_str = libspu.libs.pir_server(link, config.SerializeToString())
RuntimeError: what: 
        [external/yacl/yacl/link/transport/channel.cc:351] Get data timeout, key=root-0:1:ALLGATHER
Stacktrace:
#0 yacl::link::Context::RecvInternal()+0x7ff2a68b71f7
#1 yacl::link::AllGatherImpl<>()+0x7ff2a68b1c61
#2 yacl::link::AllGather()+0x7ff2a68b20e3
#3 spu::psi::SyncWait<>()+0x7ff2a654c54a
#4 spu::pir::PirServer()+0x7ff2a65567c4
#5 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7ff2a5359e4f
#6 pybind11::cpp_function::dispatcher()+0x7ff2a5325f06
#7 PyCFunction_Call+0x4e0212

stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7ff2a68b71f7
#1 yacl::link::AllGatherImpl<>()+0x7ff2a68b1c61
#2 yacl::link::AllGather()+0x7ff2a68b20e3
#3 spu::psi::SyncWait<>()+0x7ff2a654c54a
#4 spu::pir::PirServer()+0x7ff2a65567c4
#5 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7ff2a5359e4f
#6 pybind11::cpp_function::dispatcher()+0x7ff2a5325f06
#7 PyCFunction_Call+0x4e0212
```

alice
```
2023-12-28 08:55:58 INFO barriers.py:283 [alice] --  SenderProxyActor has successfully created.
2023-12-28 08:55:58 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 0 attemp, up to 3600 attemps.
2023-12-28 08:55:58 INFO pir.py:87 [alice] --  spu init
(SPURuntime pid=4144) 2023-12-28 08:56:00.246 [info] [default_brpc_retry_policy.cc:DoRetry:52] socket error, sleep=1000000us and retry
(SPURuntime pid=4144) 2023-12-28 08:56:01.246 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=10.1.251.75:59302} (0x0x49f8440): Connection refused [R1][E112]Not connected to 10.1.251.75:59302 yet, server_id=0'
(SPURuntime pid=4144) 2023-12-28 08:56:01.246 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
(SPURuntime pid=4144) 2023-12-28 08:56:02.246 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=10.1.251.75:59302} (0x0x49f8440): Connection refused [R1][E112]Not connected to 10.1.251.75:59302 yet, server_id=0 [R2][E112]Not connected to 10.1.251.75:59302 yet, server_id=0'
(SPURuntime pid=4144) 2023-12-28 08:56:02.247 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
```

**Comment by zimu-yuxi** [comment]
请稍等，我们复现一下。后续可能需要您的配合

**Comment by zimu-yuxi** [comment]
你好，我们目前没有复现到这个问题。请问下，我们是使用SPU的代码跑的PIR吗？

**Comment by Chrisdehe** [comment]
更正下，这个是secretflow的PIR
不是SPU的PIR哇

**Comment by Chrisdehe** [comment]
@yyf1986 hi，新年快乐！
通过复现我们没有发现“使用旧的setup目录卡死”也就是setup后二次运行query发生卡死的问题。
在您的两台机器中可能存在其他导致此问题出现的隐患，如果方便的话请将执行步骤及setup代码和query代码贴一下。
祝好！
